spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  profiles:
    active: prod


logging:
  level:
    org:
      hibernate:
        type: debug


feign:
  url: http://localhost:8075

default:
  locale: ru
  name: language

server:
  port: 8080

jwt:
  token:
    expired: 3600000
    secret: jwtsecurity
